version: "3.9"

networks:
  traefik-public:
    name: traefik-public
    external: true

services:
  web:
    image: nginxdemos/hello:0.3
    ports:
      - 9001:80
    networks:
      - traefik-public
    deploy:
      labels:
        - "traefik.enable=true"
        - "traefik.http.routers.adacoffeefordev.rule=Host(`demo.<yourdomain.tld>`)"
        - "traefik.http.routers.adacoffeefordev.entrypoints=websecure"
        - "traefik.http.routers.adacoffeefordev.tls.certresolver=letsencrypt"
        - "traefik.http.services.adacoffeefordev.loadbalancer.server.port=80"
      replicas: 1
      update_config:
        parallelism: 2
        order: start-first
        failure_action: rollback
        delay: 10s
      rollback_config:
        parallelism: 0
        order: stop-first
      restart_policy:
        condition: any
        delay: 5s
        max_attempts: 3
        window: 120s

